export * from "./auth.controller";
export * from "./user.controller";
export * from "./salle.controller";
export * from "./exercice.controller";
export * from "./exercice-type.controller";
export * from "./badge.controller";
export * from "./defi.controller";
export * from "./seance-entrainement.controller";
export * from "./suivi-defi.controller";